import { FileText, PieChart, Receipt, Download, Mail, Filter } from "lucide-react";

export function Reports() {
  const categories = [
    {
      title: "Payroll Register & Summaries",
      icon: FileText,
      reports: [
        { name: "Gross to Net Summary", description: "Comprehensive breakdown of all earnings, deductions, and net pay." },
        { name: "Payroll Variance Report", description: "Compare current payroll cycle against previous periods." },
        { name: "Departmental Costing", description: "Analyze payroll expenses distributed by department/cost center." }
      ]
    },
    {
      title: "Statutory Compliance",
      icon: PieChart,
      reports: [
        { name: "Monthly Tax Returns", description: "Government mandated tax withholding summaries." },
        { name: "Social Security & Pension", description: "Contributions breakdown for compliance filing." },
        { name: "Annual Earnings Report (W-2 equivalent)", description: "Year-end employee earnings and tax statements." }
      ]
    },
    {
      title: "Payslips & Employee Documents",
      icon: Receipt,
      reports: [
        { name: "Batch Print Payslips", description: "Generate PDF payslips for physical distribution." },
        { name: "Email Distribution Logs", description: "Track delivery status of digital payslips." },
        { name: "Leave Balance Statements", description: "Accrued and utilized leave time reporting." }
      ]
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Reporting Center</h1>
          <p className="text-sm text-slate-500 mt-1">Generate payroll, statutory, and employee reports.</p>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center gap-2 px-4 py-2 bg-white text-slate-700 font-medium rounded-lg border border-slate-200 hover:bg-slate-50 transition-colors">
            <Filter size={18} /> Filter Options
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors shadow-sm hover:shadow">
            <Mail size={18} /> Email Payslips
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {categories.map((category, idx) => (
          <div key={idx} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
            <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center gap-3">
              <div className="p-2 bg-white rounded-lg shadow-sm text-blue-600">
                <category.icon size={20} />
              </div>
              <h2 className="font-bold text-slate-900">{category.title}</h2>
            </div>
            
            <div className="p-4 flex-1 flex flex-col gap-4">
              {category.reports.map((report, rIdx) => (
                <div key={rIdx} className="group p-3 -mx-3 rounded-lg hover:bg-blue-50 transition-colors cursor-pointer border border-transparent hover:border-blue-100 flex items-start gap-3">
                  <div className="flex-1">
                    <h3 className="text-sm font-semibold text-slate-900 group-hover:text-blue-700">{report.name}</h3>
                    <p className="text-xs text-slate-500 mt-1">{report.description}</p>
                  </div>
                  <button className="opacity-0 group-hover:opacity-100 p-1.5 text-blue-600 hover:bg-blue-100 rounded transition-all shrink-0">
                    <Download size={16} />
                  </button>
                </div>
              ))}
            </div>
            
            <div className="p-4 border-t border-slate-100 bg-slate-50/50 mt-auto">
              <button className="w-full py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors">
                View All {category.title}
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 mt-8">
        <h3 className="text-lg font-bold text-slate-900 mb-4">Recent Reports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-slate-200">
                <th className="pb-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Report Name</th>
                <th className="pb-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Generated By</th>
                <th className="pb-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Date & Time</th>
                <th className="pb-3 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {[
                { name: "Q3 Statutory Compliance Summary", user: "John Doe", date: "Oct 25, 2026 14:30" },
                { name: "October Pre-Payroll Variance", user: "Jane Smith", date: "Oct 24, 2026 09:15" },
                { name: "Departmental Costing - September", user: "John Doe", date: "Oct 01, 2026 11:00" },
              ].map((row, i) => (
                <tr key={i} className="hover:bg-slate-50 transition-colors">
                  <td className="py-3 text-sm font-medium text-slate-900 flex items-center gap-2">
                    <FileText size={16} className="text-slate-400" />
                    {row.name}
                  </td>
                  <td className="py-3 text-sm text-slate-500">{row.user}</td>
                  <td className="py-3 text-sm text-slate-500">{row.date}</td>
                  <td className="py-3 text-right">
                    <button className="text-blue-600 hover:text-blue-800 text-sm font-medium hover:underline">Download PDF</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
